# Generated by Django 5.0.3 on 2024-03-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category_customer_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='customer',
            new_name='order',
        ),
    ]
